### ISSUE TITLE
How do i install them?

### ISSUE THREAD

**Issue by BeanTeen** [RedBrumbler/GorillaCosmetics#1]
It says I have to go to the Mod Data folder on my quest but I don't have that. Was I supposed to install something else as well?

**Comment by RedBrumbler** [comment]
you need to run the game once before trying to install cosmetic items

seeing as this has nothing to do with bugfixes for the mod I am closing this issue, for further support ask in the [Modding Discord](https://discord.gg/UntUxWxC)
